# Generated by Django 2.2 on 2022-02-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('contact', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(blank=True, max_length=225, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=225, null=True)),
                ('plain_model', models.CharField(blank=True, max_length=225, null=True)),
                ('available_seats', models.IntegerField(default=0)),
                ('from_country', models.CharField(blank=True, max_length=225, null=True)),
                ('destination', models.CharField(blank=True, max_length=225, null=True)),
                ('ticket_num', models.CharField(blank=True, max_length=225, null=True)),
                ('date_avail', models.CharField(blank=True, max_length=225, null=True)),
                ('date_flight', models.DateField(blank=True, null=True)),
                ('time_depart', models.CharField(blank=True, max_length=225, null=True)),
                ('time_land', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserve', models.DateField(blank=True, null=True)),
                ('date_cancel', models.DateField(blank=True, null=True)),
                ('cancel_booking', models.BooleanField(default=False)),
                ('cust_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Customer')),
                ('flight_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Flight')),
            ],
        ),
    ]
