# Generated by Django 3.2.12 on 2022-02-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('airline', models.CharField(blank=True, max_length=225, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=225, null=True)),
                ('plain_model', models.CharField(blank=True, max_length=225, null=True)),
                ('available_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('from_country', models.CharField(blank=True, max_length=225, null=True)),
                ('destination', models.CharField(blank=True, max_length=225, null=True)),
                ('ticket_num', models.CharField(blank=True, max_length=225, null=True)),
                ('date_avail', models.DateField(blank=True, null=True)),
                ('date_flight', models.DateField(blank=True, null=True)),
                ('time_depart', models.CharField(blank=True, max_length=225, null=True)),
                ('time_land', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reserve', models.DateField(blank=True, null=True)),
                ('date_cancel', models.DateField(blank=True, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.flight')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
