# Generated by Django 3.2.12 on 2022-02-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_flight_date_avail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cancel_booking',
            new_name='is_canceled',
        ),
    ]
