# Generated by Django 3.2.12 on 2022-02-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220219_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
